mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: cn.bdqn.itrip.pojo
#数据源的配置推荐使用Tomcat数据源，因为其性能和并发比较优秀
spring:
  servlet:
    multipart:
      max-file-size: 100MB
  mail:
    host: smtp.sina.cn
    port: 25
    username: yokangLee@sina.com
    password: a1a2a3456
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
  mvc:
    static-path-pattern: /static/**
    date-format: yyyy-MM-dd
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alx?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      initial-size: 5
      max-active: 100
      max-idle: 50
      min-idle: 45
      max-wait: 100
      remove-abandoned: true
      remove-abandoned-timeout: 180
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      num-tests-per-eviction-run: 100
logging:
  level:
    cn.bdqn.itrip.dao: debug
